### ISSUE TITLE
Incrementing the File Version for the assembly causes loading plugin for Dub's Bad Hygiene to fail

### ISSUE THREAD

**Issue by Inglix** [emipa606/ConnectedBed#2]
Since the File Version of the main assembly for this mod was incremented from `1.5.0` the plugin for Dub's Bad Hygiene fails to load. This is because the `LoadPlugin` method in `ModConfig` uses that value as part of the path to locate the correct assembly for the plugin. The actual plugin is located at `Plugins\1.5\CB_DBH.dll` but the mod is now looking for it at `Plugins\1.5.2\CB_DBH.dll`.

HugsLib Log: https://gist.github.com/Inglix/8755f29ac0735f45eb8b0d4384877956

https://github.com/emipa606/ConnectedBed/blob/384d2d30d0eb9a64f1956d02a90505bbeff231ad/Source/ConnectedBed/ModConfig.cs#L34-L51

https://github.com/emipa606/ConnectedBed/blob/384d2d30d0eb9a64f1956d02a90505bbeff231ad/Source/ConnectedBed/VNPE_ConnectedBed.csproj#L9

**Comment by emipa606** [comment]
Okay, that was a very silly solution. Should be fixed now, thanks for reporting!
